# Tuned for KVM1 (~512MB container)
listen_addresses = '*'
max_connections = 40
shared_buffers = 128MB
effective_cache_size = 256MB
maintenance_work_mem = 32MB
work_mem = 2MB
wal_buffers = 4MB
checkpoint_completion_target = 0.9
random_page_cost = 1.1
log_min_duration_statement = 500
